---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
feign:
  accessTokenUri: http://localhost:9098/auth-server/oauth/token
  clientId: clientId
  clientSecret: secret
  
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: http://localhost:9098/auth-server/.well-known/jwks.json